package org.cleargram.integration;

import org.junit.Test;
import org.cleargram.api.NoiseAction;
import org.cleargram.api.NoisePipelineOutcome;
import org.telegram.messenger.MessageObject;
import org.telegram.tgnet.TLRPC;
import java.util.ArrayList;
import static org.junit.Assert.*;

public final class TelegramFooterOnlyTextSuppressionPolicyTest {
    private static final TelegramFooterOnlyTextSuppressionPolicy.FooterClassifier MATCHER = (t,e,c,p) -> TelegramChannelFooterLinkClassifier.classifyLastLine(t,e,c,p,(chat,user)->chat.username != null && chat.username.equalsIgnoreCase(user));
    @Test public void rawProductionMappingAcceptsOnlyEligibleFooterOnlyText() { assertTrue(request(raw("https://t.me/current", null,null,null,null,null,null,null), false, channel("current"))); }
    @Test public void rawProductionMappingRejectsEachTelegramShape() {
        assertFalse(request(raw("https://t.me/current", null,1,null,null,null,null,null),false,channel("current")));
        assertFalse(request(rawContentType("https://t.me/current", 1),false,channel("current")));
        assertFalse(request(raw("https://t.me/current", new TLRPC.TL_messageMediaWebPage(),0,null,null,null,null,null),false,channel("current")));
        assertFalse(request(raw("https://t.me/current", new TLRPC.TL_messageMediaPhoto(),0,null,null,null,null,null),false,channel("current")));
        assertFalse(request(raw("https://t.me/current", null,0,"caption",null,null,null,null),false,channel("current")));
        assertFalse(request(raw("https://t.me/current", null,0,null,true,null,null,null),false,channel("current")));
        assertFalse(request(raw("https://t.me/current", null,0,null,null,true,null,null),false,channel("current")));
        assertFalse(request(raw("https://t.me/current", null,0,null,null,null,new TLRPC.TL_messageActionPinMessage(),null),false,channel("current")));
        assertFalse(request(raw("https://t.me/current", null,0,null,null,null,null,new TLRPC.TL_replyInlineMarkup()),false,channel("current")));
        assertFalse(request(raw("https://t.me/current", null,0,null,null,null,null,null,new TLRPC.TL_messageFwdHeader()),false,channel("current")));
        assertFalse(request(raw("https://t.me/current", null,0,null,null,null,null,null,null,new TLRPC.TL_messageReplyHeader()),false,channel("current")));
    }
    @Test public void mediaEligibilityUsesProductionSeam() { assertTrue(TelegramFooterOnlyTextSuppressionPolicy.isMediaFree(null));assertTrue(TelegramFooterOnlyTextSuppressionPolicy.isMediaFree(new TLRPC.TL_messageMediaEmpty()));assertFalse(TelegramFooterOnlyTextSuppressionPolicy.isMediaFree(new TLRPC.TL_messageMediaWebPage()));assertFalse(TelegramFooterOnlyTextSuppressionPolicy.isMediaFree(new TLRPC.TL_messageMediaPhoto()));assertFalse(TelegramFooterOnlyTextSuppressionPolicy.isMediaFree(new TLRPC.TL_messageMediaDocument()));assertFalse(TelegramFooterOnlyTextSuppressionPolicy.isMediaFree(new TLRPC.TL_messageMediaPoll())); }
    @Test public void validRetainedPrefixFailsOpenWithoutMutation() { TelegramFooterOnlyTextSuppressionPolicy.Candidate c=raw("body\nhttps://t.me/current",null,null,null,null,null,null,null); c.entities.get(0).offset=5;c.entities.get(0).length="https://t.me/current".length();assertFalse(request(c,false,channel("current")));assertEquals(5,c.entities.get(0).offset); }
    @Test public void textUrlAndUrlFooterOnlyRequest() { assertTrue(request(raw("https://t.me/current",null,null,null,null,null,null,null),false,channel("current"))); TelegramFooterOnlyTextSuppressionPolicy.Candidate c=raw("open",null,null,null,null,null,null,null);TLRPC.TL_messageEntityTextUrl u=new TLRPC.TL_messageEntityTextUrl();u.offset=0;u.length=4;u.url="https://t.me/current";c.entities.set(0,u);assertTrue(request(c,false,channel("current"))); }
    @Test public void externalForeignGroupChatAndTerminalFailOpen() { assertFalse(request(raw("https://example.com",null,null,null,null,null,null,null),false,channel("current")));assertFalse(request(raw("https://t.me/other",null,null,null,null,null,null,null),false,channel("current")));assertFalse(request(raw("https://t.me/current",null,null,null,null,null,null,null),true,channel("current")));assertFalse(request(raw("https://t.me/current",null,null,null,null,null,null,null),false,new TLRPC.TL_chat()));assertFalse(request(NoisePipelineOutcome.TERMINAL_DECISION, null,raw("https://t.me/current",null,null,null,null,null,null,null),false,channel("current")));assertFalse(request(NoisePipelineOutcome.CONTINUE_DUPLICATE_VIDEO,NoiseAction.HIDE,raw("https://t.me/current",null,null,null,null,null,null,null),false,channel("current")));assertFalse(request(NoisePipelineOutcome.CONTINUE_DUPLICATE_VIDEO,NoiseAction.COLLAPSE,raw("https://t.me/current",null,null,null,null,null,null,null),false,channel("current"))); }
    @Test public void classifierExceptionFailsOpenWithoutMutatingCandidate() { TelegramFooterOnlyTextSuppressionPolicy.Candidate c=raw("https://t.me/current",null,null,null,null,null,null,null);int offset=c.entities.get(0).offset,length=c.entities.get(0).length;assertFalse(TelegramFooterOnlyTextSuppressionPolicy.isRequested(NoisePipelineOutcome.CONTINUE_DUPLICATE_VIDEO,null,c,false,channel("current"),null,(t,e,chat,prefix)->{throw new RuntimeException("expected");}));assertEquals("https://t.me/current",c.text);assertEquals(1,c.entities.size());assertEquals(offset,c.entities.get(0).offset);assertEquals(length,c.entities.get(0).length); }
    private static TelegramFooterOnlyTextSuppressionPolicy.Candidate raw(String text, TLRPC.MessageMedia media, Integer type, CharSequence caption, Boolean sponsored, Boolean service, TLRPC.MessageAction action, TLRPC.ReplyMarkup markup, Object... headers) { ArrayList<TLRPC.MessageEntity> e=new ArrayList<>();TLRPC.TL_messageEntityUrl u=new TLRPC.TL_messageEntityUrl();u.offset=0;u.length=text.length();e.add(u);TLRPC.MessageFwdHeader f=headers.length>0?(TLRPC.MessageFwdHeader)headers[0]:null;TLRPC.MessageReplyHeader r=headers.length>1?(TLRPC.MessageReplyHeader)headers[1]:null;return TelegramFooterOnlyTextSuppressionPolicy.Candidate.fromRawTelegramShape(text,e,type==null?MessageObject.TYPE_TEXT:type,headers.length>2?(Integer)headers[2]:0,media,caption,sponsored!=null&&sponsored,service!=null&&service,action,markup,f,r); }
    private static TelegramFooterOnlyTextSuppressionPolicy.Candidate rawContentType(String text, int contentType) { TelegramFooterOnlyTextSuppressionPolicy.Candidate base=raw(text,null,null,null,null,null,null,null); return TelegramFooterOnlyTextSuppressionPolicy.Candidate.fromRawTelegramShape(base.text,base.entities,MessageObject.TYPE_TEXT,contentType,null,null,false,false,null,null,null,null); }
    private static boolean request(TelegramFooterOnlyTextSuppressionPolicy.Candidate c,boolean g,TLRPC.Chat chat){return request(NoisePipelineOutcome.CONTINUE_DUPLICATE_VIDEO,null,c,g,chat);} private static boolean request(NoisePipelineOutcome o,NoiseAction a,TelegramFooterOnlyTextSuppressionPolicy.Candidate c,boolean g,TLRPC.Chat chat){return TelegramFooterOnlyTextSuppressionPolicy.isRequested(o,a,c,g,chat,null,MATCHER);} private static TLRPC.TL_channel channel(String n){TLRPC.TL_channel c=new TLRPC.TL_channel();c.username=n;return c;}
}
