package org.cleargram.integration;

import org.junit.Test;
import org.cleargram.api.NoiseAction;
import org.cleargram.api.NoisePipelineOutcome;
import org.telegram.messenger.MessageObject;
import org.telegram.tgnet.TLRPC;
import java.util.ArrayList;
import static org.junit.Assert.*;

public final class TelegramFooterOnlyTextBindIntegrationTest {
    private static final TelegramFooterOnlyTextSuppressionPolicy.FooterClassifier MATCHER=(t,e,c,p)->TelegramChannelFooterLinkClassifier.classifyLastLine(t,e,c,p,(chat,user)->chat.username.equalsIgnoreCase(user));
    @Test public void preparationDelegatesBoundaryAndTerminalGates() { assertTrue(prepare(candidate("https://t.me/current"),false,NoisePipelineOutcome.CONTINUE_DUPLICATE_VIDEO,null).isRequested());assertFalse(prepare(candidate("body\nhttps://t.me/current",5),false,NoisePipelineOutcome.CONTINUE_DUPLICATE_VIDEO,null).isRequested());assertFalse(prepare(candidate("https://t.me/current"),false,NoisePipelineOutcome.TERMINAL_DECISION,null).isRequested());assertFalse(prepare(candidate("https://t.me/current"),false,NoisePipelineOutcome.CONTINUE_DUPLICATE_VIDEO,NoiseAction.HIDE).isRequested());assertFalse(prepare(candidate("https://t.me/current"),false,NoisePipelineOutcome.CONTINUE_DUPLICATE_VIDEO,NoiseAction.COLLAPSE).isRequested()); }
    @Test public void noMatchExceptionAndGroupFailOpenWithoutMutation() { TelegramFooterOnlyTextSuppressionPolicy.Candidate c=candidate("https://example.com");assertFalse(prepare(c,false,NoisePipelineOutcome.CONTINUE_DUPLICATE_VIDEO,null).isRequested());TelegramFooterOnlyTextSuppressionPolicy.Candidate ok=candidate("https://t.me/current");assertFalse(TelegramFooterOnlyTextBindIntegration.prepare(NoisePipelineOutcome.CONTINUE_DUPLICATE_VIDEO,null,ok,false,channel(),null,(t,e,ch,p)->{throw new RuntimeException();}).isRequested());assertEquals("https://t.me/current",ok.text);assertFalse(prepare(ok,true,NoisePipelineOutcome.CONTINUE_DUPLICATE_VIDEO,null).isRequested()); }
    @Test public void applicationGateIsPureAndFailOpen() { TelegramFooterOnlyTextBindIntegration.Request requested=prepare(candidate("https://t.me/current"),false,NoisePipelineOutcome.CONTINUE_DUPLICATE_VIDEO,null);assertFalse(TelegramFooterOnlyTextBindIntegration.shouldApply(null,true,true));assertFalse(TelegramFooterOnlyTextBindIntegration.shouldApply(prepare(candidate("https://example.com"),false,NoisePipelineOutcome.CONTINUE_DUPLICATE_VIDEO,null),true,true));assertTrue(TelegramFooterOnlyTextBindIntegration.shouldApply(requested,true,true));assertFalse(TelegramFooterOnlyTextBindIntegration.shouldApply(requested,false,true));assertFalse(TelegramFooterOnlyTextBindIntegration.shouldApply(requested,true,false));assertTrue(TelegramFooterOnlyTextBindIntegration.shouldApply(requested,true,true)); }
    @Test public void textUrlPreparationPreservesEntity() { TelegramFooterOnlyTextSuppressionPolicy.Candidate c=candidate("open",0);TLRPC.TL_messageEntityTextUrl u=new TLRPC.TL_messageEntityTextUrl();u.offset=0;u.length=4;u.url="https://t.me/current";c.entities.set(0,u);assertTrue(prepare(c,false,NoisePipelineOutcome.CONTINUE_DUPLICATE_VIDEO,null).isRequested());assertEquals("open",c.text);assertEquals(0,u.offset);assertEquals(4,u.length);assertEquals("https://t.me/current",u.url); }
    private static TelegramFooterOnlyTextBindIntegration.Request prepare(TelegramFooterOnlyTextSuppressionPolicy.Candidate c,boolean g,NoisePipelineOutcome o,NoiseAction a){return TelegramFooterOnlyTextBindIntegration.prepare(o,a,c,g,channel(),null,MATCHER);} private static TelegramFooterOnlyTextSuppressionPolicy.Candidate candidate(String t){return candidate(t,0);} private static TelegramFooterOnlyTextSuppressionPolicy.Candidate candidate(String t,int offset){ArrayList<TLRPC.MessageEntity> e=new ArrayList<>();TLRPC.TL_messageEntityUrl u=new TLRPC.TL_messageEntityUrl();u.offset=offset;u.length=t.length()-offset;e.add(u);return TelegramFooterOnlyTextSuppressionPolicy.Candidate.fromRawTelegramShape(t,e,MessageObject.TYPE_TEXT,0,null,null,false,false,null,null,null,null);} private static TLRPC.TL_channel channel(){TLRPC.TL_channel c=new TLRPC.TL_channel();c.username="current";return c;}
}
